feet: about-section
MichalStanaszek/projekt-html-css-group-5 pull request #23
Opened 2023-04-02 16:15 UTC by pawelwiteckiwawrzyniak

Added whole about-section

2023-04-02 16:19 UTC, pawelwiteckiwawrzyniak commented
Zrobiłem na własne potrzeby ogólną klase .section-title w about.scss. Jak stwierdzisz, że wszystko git to możesz ją dodać do generals (media query też już dodałem - fell free to add them as well), żeby każdy mógł ją wykorzystać (jest już cała ostylowana + marginesy). Responsywność zrobiłem w stylu adaptacyjnym (według mnie prościej, ale jak trzeba to zmienię na responsywną)

2023-04-02 16:24 UTC, pawelwiteckiwawrzyniak commented
*do _general.scss, ewentualnie zrobić kolejny plik i.e. _section-title.scss

2023-04-02 17:14 UTC, MichalStanaszek requested changes

2023-04-02 17:14 UTC, MichalStanaszek commented on src/sass/partials/_about.scss
> +    font-size: 16px;
Powtórzenie bazowych styli przeglądarki. Można usunąć tą linię.

2023-04-02 17:14 UTC, MichalStanaszek commented on src/sass/partials/_about.scss
> +    color: #000000;
Powtórzenie bazowych styli przeglądarki. Można usunąć tą linię.

2023-04-02 17:14 UTC, MichalStanaszek commented on src/sass/partials/_about.scss
> +    margin-bottom: 80px;
Ten margin jest nadpisywany przez "--about". Myślę, że można się jej pozbyć

  &--about {
      margin-bottom: 26px;
    }

2023-04-03 20:51 UTC, MichalStanaszek approved these changes

2023-04-03 20:51 UTC, merged